-- This migration previously contained test data inserts that caused foreign key constraint violations.
-- The test data has been removed to allow the database schema to be pushed successfully.
-- Users and products should be created via the application's UI.
