// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://rtvsinrxboyamtrglciz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0dnNpbnJ4Ym95YW10cmdsY2l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MTkzNjgsImV4cCI6MjA2ODk5NTM2OH0.zgLk5vue5rt7FV5ayNQ98fjUfKTdwUdccsBVJ2d_xAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  },
);
